phases:
  main:
    name: Main
    start: 2023-05-26
    end: 2023-09-01
    description: Main phase

max_submissions_per_day: 2
max_submissions: 20

n_samples: 10000
n_targets: 100
target_min_hh: 5

tasks:
  generator:
    - mst
    - pategan
    - privbayes
  epsilon:
    - 1
    - 10
    - 100
    - 1000
