CAT_COLUMNS = [
    "agechild",
    "citistat",
    "cow1",
    "female",
    "ftptstat",
    "married",
    "mind16",
    "mocc10",
    "statefips",
    "wbhaom",
]

ORD_COLUMNS = ["gradeatn", "faminc"]

METADATA = {
    "columns": [
        {"name": "age", "type": "Integer", "min": 0, "max": 64},
        {
            "name": "agechild",
            "type": "Categorical",
            "size": 15,
            "i2s": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        },
        {"name": "citistat", "type": "Categorical", "size": 4, "i2s": [0, 1, 2, 3, 4]},
        {"name": "female", "type": "Categorical", "size": 1, "i2s": [0, 1]},
        {"name": "married", "type": "Categorical", "size": 1, "i2s": [0, 1]},
        {"name": "ownchild", "type": "Integer", "min": 0, "max": 11},
        {"name": "wbhaom", "type": "Categorical", "size": 5, "i2s": [0, 1, 2, 3, 4, 5]},
        {
            "name": "gradeatn",
            "type": "Ordinal",
            "size": 15,
            "i2s": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        },
        {
            "name": "cow1",
            "type": "Categorical",
            "size": 7,
            "i2s": [0, 1, 2, 3, 4, 5, 6, 7],
        },
        {
            "name": "ftptstat",
            "type": "Categorical",
            "size": 8,
            "i2s": [0, 1, 2, 3, 4, 5, 6, 7, 8],
        },
        {
            "name": "statefips",
            "type": "Categorical",
            "size": 50,
            "i2s": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                31,
                32,
                33,
                34,
                35,
                36,
                37,
                38,
                39,
                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47,
                48,
                49,
                50,
            ],
        },
        {"name": "hoursut", "type": "Integer", "min": 0, "max": 198},
        {
            "name": "faminc",
            "type": "Ordinal",
            "size": 14,
            "i2s": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
        },
        {
            "name": "mind16",
            "type": "Categorical",
            "size": 15,
            "i2s": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
        },
        {
            "name": "mocc10",
            "type": "Categorical",
            "size": 9,
            "i2s": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        },
    ]
}

DOMAIN = {
    "age": 65,
    "agechild": 16,
    "citistat": 5,
    "female": 2,
    "married": 2,
    "ownchild": 12,
    "wbhaom": 6,
    "gradeatn": 16,
    "cow1": 8,
    "ftptstat": 9,
    "statefips": 51,
    "hoursut": 199,
    "faminc": 15,
    "mind16": 16,
    "mocc10": 10,
}
